<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class UpdateEmailTemplate extends Migration
{
    public function up()
    { 
        $db = \Config\Database::connect();
        $builder = $db->table('email_templates');

        $templates = [
            'provider_disapproved' => '<p>Dear [[provider_name]] </p>,<p>I regret to inform you that your registration request has been declined. After careful review and consideration, we have determined that your offerings do not align with our current needs or standards.</p><p>While we appreciate your interest in partnering with us, we believe it is in both of our best interests to explore other opportunities that better fit our requirements at this time.</p><p>Please know that this decision was not made lightly, and we genuinely value the effort you put into your application. We encourage you to continue pursuing opportunities that align more closely with your expertise and offerings.</p><p>Thank you for your understanding. Should you have any questions or require further clarification, please do not hesitate to reach out.</p><br><p>I wish you all the best in your future endeavors.</p><br><br><p>Warm regards,</p><p>[[company_name]]</p><p>[[company_contact_info]]</p>',
            'withdraw_request_approved' => '<p>Dear [[Provider Name]],</p><p>We are pleased to inform you that your withdrawal request has been approved. If you have any questions or concerns regarding this transaction, please do not hesitate to contact us.<br> Thank you for choosing our services. We look forward to providing you with excellent service in the future.</p><p>Your Request is for: [[Amount]] [[Currency]].</p><br><br><p>Best Regards,<p><p>[[Company Name]]</p>',
            'withdraw_request_disapproved' => '<p>Dear [[Provider Name]],</p><p>We regret to inform you that your withdrawal request has been disapproved. If you have any questions or concerns regarding this decision, please do not hesitate to contact us.</p><p> Thank you for choosing our services. We look forward to providing you with excellent service in the future.</p><p>Your Request is for: [[Amount]] [[Currency]].</p><br><br><p>Best Regards,</p><p> [[Company Name]]</p>',
            'payment_settlement' => '<p>Dear [[provider_name]],</p><p>I am writing to confirm that we have credited the agreed upon amount of [[currency]][[amount]] to your account, as per our agreement. This payment settles the outstanding balance for the services provided by your company.</p><p>We understand the importance of timely payments for maintaining a healthy business relationship, and we strive to meet our payment obligations promptly. Please check your account and confirm that the payment has been received.</p><p>If you have any questions or concerns, please do not hesitate to contact us.</p><p>[[company_contact_info]]</p><br><p>Thank you for your prompt attention to this matter. We look forward to continuing our mutually beneficial partnership.</p> <br><br><p>Best Regards,</p><p>[[company_name]]</p>',
            'service_disapproved' =>  '<p>Dear [[Provider Name]],</p><p>We regret to inform you that your request for service approval has been disapproved. After thorough evaluation and consideration, our team has determined that your request does not meet the necessary criteria for approval.</p><br><p>We understand that this decision may be disappointing for you, but please know that we carefully reviewed your request and made the best decision based on our policies and guidelines.</p><p>If you have any questions or concerns regarding the decision, please do not hesitate to reach out to us. We would be happy to discuss any specific concerns that you may have.</p><p>Contact us:</p><p>[[Company Contact Info]]</p><br><br><p>Best Regards,</p><p>[[Company Name]]</p>',
            'service_approved' => '<p>Dear [[Provider Name]],</p><p>I am pleased to inform you that your request for service approval has been approved. After careful review and consideration, our team has determined that your request meets all the necessary criteria and is eligible for approval.</p><p>Once again, congratulations on your approval status! We look forward to working with you and supporting your goals.</p><p>If you have any questions or concerns, please do not hesitate to contact us.</p><p>Contact Us: [[Company Contact Info]]</p><br><br><p>Best Regards,</p><p>[[Company Name]]</p>',
            'user_account_active' => '<p>Dear [[user_name]],</p><p>We are pleased to inform you that your account has been successfully activated. You can now log in to your account and start using our services.</p><p>If you have any questions or need any assistance feel free to contact us.</p><p>Thank you again for choosing our services. We look forward to doing business with you again.</p><br><br><p>Best Regards ,</p><p>[[company_name]]</p>',
            'user_account_deactive' => '<div>Dear [[user_name]]</div><div>&nbsp;</div><div>We are sorry to inform you that your account has been deactivated.</div><div>&nbsp;</div><div><div>If you have any questions or need any assistance feel free to contact us.</div></div><div><div><div>&nbsp;</div><div>Thank you again for choosing our services. We look forward to doing business with you again.</div><br><br><div>Best Regards,</div><div>[[company_name]]</div></div></div>',
            'new_booking_confirmation_to_customer' => '<p>Dear [[user_name]],</p><p>Thank you for choosing [[provider_name]]. We are pleased to confirm your booking.Booking Details:</p><br><ul><li>Booking Date:[[booking_date]]</li><li>Time:[[booking_time]]</li><li>Address:[[booking_address]]</li><li>Services include:[[booking_service_names]]</li></ul><br><p>We look forward to serving you. If you have any questions or need to make changes to your booking, please do not hesitate to contact us at [Contact Information].</p><br><br><p>Best regards,</p><p>[[company_name]]</p><p>[[company_contact_info]]</p>',
            'new_booking_received_for_provider' => '<p>Dear [[provider_name]] ,</p><p>We are delighted to inform you that a new booking has been received through our platform.</p><p>Booking Details:</p><br><ul><li>Service:[[booking_service_names]]</li><li>Booking Date: [[booking_date]]</li><li>Time: [[booking_time]]</li><li>Customer:[[user_name]]</li></ul><br><p>Please ensure that you are prepared for the appointment and ready to provide exceptional service to our valued customer.</p><p>If you have any questions or require further information regarding this booking, feel free to reach out to us.</p><p>Thank you for being a part of our service and for your commitment to excellence.</p><br><br><p>Best regards,</p><p>[[company_name]]</p><p>[[company_contact_info]]</p>',
            'provider_update_information' => '<p>Dear [[company_name]]</p><br><p>I hope this message finds you well.</p><p>I wanted to inform you that [Provider Name] has recently updated their details. Please find the updated information below:</p><p>Provider ID: [[provider_id]]</p><br><p>[[provider_name]] has taken the initiative to ensure that their information is accurate and up-to-date in our records. If there are any further steps required from our end regarding this update, please let us know.</p><br><p>Thank you for your attention to this matter.</p><br><br><p>Best regards,</p><p>[[company_name]]</p><p>[[company_contact_info]]</p>',
            'new_provider_registerd' => '<p>Subject: New Provider Registered</p><br><p>Dear [[company_name]],</p><br><br><p>I hope this email finds you well. I am pleased to inform you that a new provider has registered with us. Here are the details of the new registration:</p><p>Provider Name:[[provider_name]]</p><p>Provider ID:[[provider_id]]</p><br><p>We welcome [[provider_name]] to our platform and look forward to exploring potential collaborations with them. Kindly review the provided information and proceed with the necessary steps to onboard them into our system.</p><p>If you require any further details or assistance regarding this registration, please do not hesitate to reach out to me.</p><p>Thank you for your attention to this matter.</p><br><br><p>Best regards,</p><p>[[company_name]]</p><p>[[company_contact_info]]</p>'
        ];  

        foreach ($templates as $type => $template) {
            $builder->where('type', $type)
                    ->update(['template' => $template]);
        }

    }

   
    public function down()
    {
        
    }
}
